### ISSUE TITLE
Feature request: menu items reorder

### ISSUE THREAD

**Issue by yungaro** [kzhovn/obsidian-customizable-menu#13] opened 2022-04-08 07:59 UTC
It will be very useful if in the config page of the plugin, it could allow to move (drag and drop) items. An obsidian plugin that has this kind of feature is cMenu from Chetachi, if it helps. Anyway, the plugin is incredibly useful as it is, congratulations.

**Comment by kzhovn** [comment] 2022-06-05 21:50
Duplicate of #8, closing in favor of that one.

**Closed by kzhovn** 2022-06-05 21:50 UTC
Labels: maybe
