### ISSUE TITLE
Feature Request: customize the names of the commands

### ISSUE THREAD

**Issue by u2003** [kzhovn/obsidian-customizable-menu#11] opened 2022-01-06 04:19 UTC
Some commands can be too long and cause visual redundancy to an extent. I wonder if you could please add a feature that allows users to customize the names of the commands that appear in the right-click menu. I would be more than grateful if you could take my advice into consideration!

**Comment by kzhovn** [comment] 2022-05-04 20:50
Duplicate of #6 .

**Closed by kzhovn** 2022-05-04 20:50 UTC
